### ISSUE TITLE
Labs 005-6 - Vue Router Nav in Immersive Mode

### ISSUE THREAD

**Issue by vrhermit** [vrhermit/Canvatorium#6]
Router Nav to Lab 006 (not working). 
Testing cross-scene navigation with Router and Window.location.
- I'm not sure if the issue is in Vue Router or on Babylon JS.
- Placing this idea on hold for now.
- While Router may not work, I can brute force my way to other scenes with \`window.location.assign("/lab006")\`

**Comment by werkflo** [comment]
Hey, Joe!
